name: "wally"
mode: "debug"
config_path: "srv/wally"
addr: "6565"

consul:
  host: "127.0.0.1"
  port: 8500

mysql:
  dsn: "root:123@tcp(127.0.0.1:3306)/video_server?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"
  max_open_conn: 20
  max_idle_conn: 10
  max_conn_life_time: 100

redis:
  addr: "127.0.0.1:6379"
  password: ""
